### ISSUE TITLE
Brainstorm - Project Titles

### ISSUE THREAD

**Issue by Dawnabelle** [dymaptic/ml-site-jekyll#20]
Currently: 

Wildlife in the Road
Authentic Neighborhood Food Finder
Farmers Market Finder
Vote with Ease
Frontier Series of Risk Assessment Software

Do we love them? Do we hate them? Let me know and I'll update them.

**Comment by morehavoc** [comment]
@Dawnabelle 
I like these.  Here are a few more that I'm thinking about that we can add soon:

These could probably be white papers too.

**Quarter-Quarter Boundary Generation**
This was a project I did a while back, but it allows the user to covert land blocks into Quarters or Quarter-Quarters.  I have some documentation on this we can use, we own it so we can do whatever we want here.

**Custom Field Data Collection - When off-the-shelf isn't good enough**
I'm talking about the Audubon app here.  Basically I'm thinking about making the argument that Survey123, Fulcrum, and other off the shelf apps can't handle the complex interactions that you sometimes need, like what we have in the data collection app for Audubon.  Basically that paper forms are extremely efficient and easy for users to fill out, and sometimes its not possible for generic software to be able to compete with that efficiency, instead you need something more sophisticated, more specialized.  And if that's your business, then its worth the investment to be as efficient as possible.  **Note: it might also be fun to do an article in the future about the true cost of custom software vs purchased software when done "as a service" like we do**

**Data Management - When you need to edit 50 attributes, not 10**
I'm thinking of the RoW app here, you cound't do this in ArcGIS Online (Well you can, but the edit interface is poor, it's just a list of attributes).  So we built a custom layout that lets them edit large volumes of attributes at once, including related records from a single interface.  This means stuff get done faster, with fewer errors and the data is centralized for automated reporting.  Something like that.

**Custom Devices - What to do when you need access to devices an the out of the box solutions don't do it?**
I'm thinking about the Android app that Mark is working on here.  Basically the standard out of the box software offerings can't connect to GPS (some can) and Multimeters, and other devices.  But we can bridge that gap, making the data collection process more efficient than before and less error prone, making the investment in the software worth while because you (our client) can deliver better data, faster.
